version: '3'
services:
  sql-dock:
    container_name: SQLDock
    image: mysql
    ports:
      - "32001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: skyrim
  py-dock:
    container_name: PyDock
    links:
      - "sql-dock"
    build: ./
    image: myplex
    ports:
      - "5001:5000"